services:
  app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    image: inventaris-backend:latest
    container_name: backend-inventaris_app
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      - APP_NAME=inventaris
      - APP_ENV=local
      - APP_KEY=
      - APP_DEBUG=true
      - APP_TIMEZONE=Asia/Jakarta
      - APP_URL=https://api-inventaris.matradipti.org
      - DB_CONNECTION=pgsql
      - DB_HOST=inventaris_db
      - DB_PORT=5432
      - DB_DATABASE=inventaris
      - DB_USERNAME=admin
      - DB_PASSWORD=inventory
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    depends_on:
      - inventaris_db
    networks:
      - inventaris-network
      - caddy_net

  inventaris_db:
    image: postgres:15
    container_name: inventaris_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=inventaris
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=inventory
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - inventaris-network

volumes:
  postgres_data:

networks:
  inventaris-network:
    driver: bridge
  caddy_net:
    external: true